version: '3.8'

services:
  db:
    container_name: shortener_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    env_file: .env
    ports:
      - "6321:5432"
    volumes:
      - db:/var/lib/postgresql/data
  api:
    container_name: shortener_api
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
volumes:
  db:
    name: shortener_db