version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: shorten
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: q6J-LIFa6t
    ports:
      - "5432:5432"
